---
type: map
required: true

schema;pid_val:
    type: map
    func: unit_overall
    required: true

    map:
        name:
            type: str
            required: true

        bytes:
            type: any
            func: bytes
            required: true

        unit:
            type: str
            func: unit_single

        expr: &expr-node
            type: str
            func: infix

        signed:
            type: bool

        unknown:
            type: bool
            # If specifying this, we are just tagging it as an
            # unknown PID. If we knew how to parse it, we would
            # specify how to parse the PID using the other methods
            # like bitmap, expr, etc.
            enum:
                - true

        bitmap:
            type: seq
            matching: any
            seq:
                - type: map
                  func: bitmap_rule_node
                  map:
                      name: &name-node
                          type: str
                      bits: &bits-node
                          type: any
                          func: range_or_int
                          required: true
                      rule:
                          type: str
                          enum:
                              - flag
                              - map
                              - range-map
                              - value
                          required: true
                      flag:
                          type: any
                          func: flag
                      map:
                          # checked by bitmap_rule_node
                          type: any
                      range-map:
                          # checked by bitmap_rule_node
                          type: any
                      # no map needed for the value rule

                - type: map
                  map:
                      name: *name-node
                      bits: *bits-node
                      expr:
                          <<: *expr-node
                          required: true

                - type: map
                  func: switch
                  map:
                      name: *name-node
                      bits: *bits-node
                      switch:
                          type: map
                          map:
                              =:
                                  include: pid_val
                          required: true

map:
    mode:
        type: int
        range:
            min: 0
        required: true

    pids:
        type: map
        required: true
        func: non_negative_int_keys

        map:
            =:
                include: pid_val
